Checkout customer information
diffblue/ecommerce-demo pull request #16
Opened 2018-01-31 16:27 UTC by paulkennethkent

Checkout now CTA on cart page links to checkout page
Checkout page structure added
Validate and submit form
Redirect to payment page

2018-01-31 16:33 UTC, JohnLBergqvist requested changes
Update the copyright date to 2018 on the relevant pages.

2018-02-01 09:15 UTC, Charliemowood approved these changes

2018-02-01 09:17 UTC, paulkennethkent commented
@JohnBergqvist and @Charliemowood copyright has now been updated.

2018-02-02 08:33 UTC, JohnLBergqvist approved these changes

2018-02-02 10:44 UTC, jgwilson42 requested changes

2018-02-02 10:44 UTC, jgwilson42 commented on README.md
> +copyright 2016-2018 DiffBlue limited. All rights reserved.
Please could you correct the capitalisation of 'Copyright'?

2018-02-02 10:44 UTC, jgwilson42 commented on README.md
> +copyright 2016-2018 DiffBlue limited. All rights reserved.
Please do this throughout

2018-02-02 10:44 UTC, jgwilson42 commented on src/main/java/com/diffblue/demo/ecommerce/controllers/CheckoutController.java
> +package com.diffblue.demo.ecommerce.controllers;
Please add a copyright notice

2018-02-02 10:44 UTC, jgwilson42 commented on src/main/java/com/diffblue/demo/ecommerce/forms/AddressForm.java
> +package com.diffblue.demo.ecommerce.forms;
Please add a copyright notice

2018-02-02 10:44 UTC, jgwilson42 commented on src/main/java/com/diffblue/demo/ecommerce/forms/CustomerForm.java
> +package com.diffblue.demo.ecommerce.forms;
Please add a copyright notice

2018-02-02 10:44 UTC, jgwilson42 commented on src/main/java/com/diffblue/demo/ecommerce/models/Cart.java
> -package com.diffblue.demo.ecommerce;
Please add a copyright notice

2018-02-05 09:53 UTC, paulkennethkent commented
@jgwilson42 - Changes made throughout, please re-review.

2018-02-06 09:52 UTC, jgwilson42 approved these changes

2018-02-06 10:30 UTC, merged