Implemented tax and basic sizing
diffblue/ecommerce-demo pull request #18
Opened 2018-03-07 11:44 UTC by paulkennethkent

Tax is added to all products except when the object size and category match the exempt criteria. Sizing implementation can be improved but I think this should be considered when we work on stock control feature, which will require big changes to the models.

2018-03-08 14:41 UTC, JohnLBergqvist requested changes

2018-03-08 14:41 UTC, JohnBergqvist commented on src/main/resources/templates/ProductPage.html
> +                        <option value="Adults">Adult</option>
The value here should be `Adult`, no?

2018-03-09 16:07 UTC, JohnLBergqvist approved these changes

2018-03-13 06:57 UTC, jgwilson42 requested changes
Please could you replace BigDecimal with double?

2018-03-15 14:51 UTC, peterschrammel requested changes
Commit 
"Merge branch 'master' into cart-tax" should be removed by rebasing the branch on master.

2018-03-15 14:51 UTC, peterschrammel commented on src/main/java/com/diffblue/demo/ecommerce/models/Order.java
> +  public Order(String orderRef, String firstName, String lastName,
trailing whitespace

2018-03-15 14:51 UTC, peterschrammel commented on src/main/java/com/diffblue/demo/ecommerce/models/OrderItem.java
> +// Copyright 2016-2018 DiffBlue limited. All rights reserved.
Diffblue (all files)

2018-03-15 14:51 UTC, peterschrammel commented on src/main/java/com/diffblue/demo/ecommerce/models/Cart.java
> +
spurious newlines

2018-03-15 14:51 UTC, peterschrammel commented on src/main/java/com/diffblue/demo/ecommerce/models/Cart.java
> +  private BigDecimal tax;
Shouldn't this be double for now?

2018-03-15 14:51 UTC, peterschrammel commented on src/main/java/com/diffblue/demo/ecommerce/models/Cart.java
> -
In a proper dev workflow these fixes should be squashed into the commit that created the problem in the first place (if this commit is in the same PR).

2018-03-15 14:51 UTC, peterschrammel commented on src/main/resources/templates/ProductPage.html
> +                        <option value="Adult">Adult</option>
squash this into the original commit

2018-03-15 14:54 UTC, peterschrammel commented
Note: In a proper dev workflow these fixes should be squashed into the commit that created the problem in the first place (if this commit is in the same PR). I'm reviewing PRs commit by commit - if something is fixed up in a later commit I will still have put a comment on the earlier commit which then appears as 'outdated'.

2018-03-16 08:54 UTC, peterschrammel approved these changes
LGTM

2018-03-16 09:20 UTC, merged