Default template created to avoid repetition
diffblue/ecommerce-demo pull request #4
Opened 2017-10-11 16:36 UTC by sara-db

- Added default.html which contains/will contain default layout to be reused when creating a new page.
- ProductList and error pages changed to use the default layout
- home page (index.html) *is not* using the default layout

2017-10-11 19:39 UTC, jgwilson42 requested changes
Please could you ensure that all files have a copyright notice? For those that inherit from the default.html when viewed on the site it would make sense to have it as a comment in the file.

2017-10-16 15:01 UTC, paulkennethkent approved these changes

2017-10-20 16:39 UTC, forejtv approved these changes

2017-10-22 05:48 UTC, jgwilson42 approved these changes

2017-10-24 09:29 UTC, merged