Schema update
diffblue/ecommerce-demo pull request #8
Opened 2017-11-02 18:19 UTC by sara-db

Product id changed to integer auto increment (identity used).

2017-11-07 08:48 UTC, jgwilson42 requested changes
Hi Sara,

Is it possible to make the ID auto increment but keep the format PRODxxx where xxx is the auto incremented number, padded with leading zero's as appropriate?

Thanks,
James

2017-11-07 10:41 UTC, sara-db commented
Hi @jgwilson42,

It is not possible to have an attribute using auto-increment with a prefix.

Some ways around this, which I do not recommend, is to create other attribute e.g. product reference that is created as null and then updated based on the auto-increment id with the prefix, however to achieve it is not straightforward. 

I suggest we do this on the application level by having a getProductRef method that would return the concatenation of the prefix and the id.

Please let me know how you want me to proceed.

Thanks,
Sara

2017-11-09 13:31 UTC, paulkennethkent approved these changes

2017-11-10 09:29 UTC, jgwilson42 approved these changes
Looks good, please could you squash the commits before merging?

2017-11-10 13:48 UTC, merged